# Generated by Django 4.0.4 on 2022-04-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=40)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
